import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import { Stack, Button } from "@mui/material";

import * as React from "react";
const inter = Inter({ subsets: ["latin"] });

//recoil
import { useSetRecoilState } from "recoil";
import { QnBnkAtom, EdittedQnBnkAtom } from "../state/quizState";
import { RecordsAtom } from "../state/recordsState";
import { BoldfaceAtom } from "../state/bfState";

//utils
import boldfaces from "../utils/bf.json";

export default function Home() {
  const setRS = useSetRecoilState(RecordsAtom);
  const setQnBnk = useSetRecoilState(QnBnkAtom);
  const setEdittedQnBnk = useSetRecoilState(EdittedQnBnkAtom);
  const setBF = useSetRecoilState(BoldfaceAtom);

  React.useEffect(() => {
    // GET request using axios inside useEffect React hook
    //getData('records', '/records?q={}&h={"$orderby": {"Valid": -1, "User": 1 }}');
    //getData('QnBank', '/quiz');
    setBF(boldfaces);
  });
  return (
    <>
      <Head>
        <title>Enforcer App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
    </>
  );
}
